controller_list:
  - name: fake_right_arm_controller
    joints:
      - ra_1_joint
      - ra_2_joint
      - ra_3_joint
      - ra_4_joint
      - ra_5_joint
      - ra_6_joint
      - ra_7_joint
  - name: fake_left_arm_controller
    joints:
      - la_1_joint
      - la_2_joint
      - la_3_joint
      - la_4_joint
      - la_5_joint
      - la_6_joint
      - la_7_joint
  - name: fake_right_gripper_controller
    joints:
      - ra_grip_left
      - ra_grip_right
  - name: fake_left_gripper_controller
    joints:
      - la_grip_left
      - la_grip_right