controller_list:
  - name: fake_right_arm_controller
    joints:
      - ra_1_joint
      - ra_2_joint
      - ra_3_joint
      - ra_4_joint
      - ra_5_joint
      - ra_6_joint
      - ra_7_joint
  - name: fake_right_gripper_controller
    joints:
      - ra_7_joint